Experimental plugin api
Mm2PL/dankerino pull request #106
Opened 2021-08-16 10:39 UTC by Mm2PL

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

2021-08-16 15:06 UTC, Mm2PL commented
- [ ] List plugins somewhere in the UI.

2021-08-18 13:21 UTC, Mm2PL commented
Plugins go in `path/to/Chatterino_config/Plugins/`.

2021-08-29 19:49 UTC, zneix requested changes
Most nitpicks / suggested changes were mentioned on stream; A few of these that I can remember on top of my head are:
- Reduce the amount of hardcoded "magic strings / numbers"
- Make it impossible for plugins to access (read / write) settings outside of `/plugins` block


Also, the thing that obv doesn't work are the timeouts in http requests, these should be looked into.
And possibly, increase the timeout value on the `supinic.com` call from 5s, because it seems to exceed this value quite often (based on my testing). Maybe 10/15 seconds will cut it.

2021-08-29 19:49 UTC, zneix commented on src/singletons/Plugins.cpp
> +            qDebug() << "Loaded" << fileName;
Use Qt-categorized logging (in all places in this file).

2021-12-07 21:48 UTC, Mm2PL commented
Will rewrite for chaiscript (or lua whichever is less cancer to use)

2023-02-28 20:49 UTC, closed without merging